# Generated by Django 5.0.1 on 2024-03-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.review'),
        ),
    ]
