# Generated by Django 5.0.1 on 2024-03-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_portal_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
