# Generated by Django 5.0.1 on 2024-03-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.review'),
        ),
    ]
