# Generated by Django 5.0.1 on 2024-03-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_remove_review_article_article_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.review'),
        ),
    ]
