# Generated by Django 5.0.1 on 2024-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/articles'),
        ),
    ]
