# Generated by Django 5.0.1 on 2024-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/articles'),
        ),
    ]
