# Generated by Django 5.0.1 on 2024-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_remove_article_image_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/articles'),
        ),
    ]
