# Generated by Django 5.0.1 on 2024-03-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2),
        ),
    ]
