# Generated by Django 5.0.1 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[(1.0, '★☆☆☆☆ (1/5)'), (2.0, '★★☆☆☆ (2/5)'), (3.0, '★★★☆☆ (3/5)'), (4.0, '★★★★☆ (4/5)'), (5.0, '★★★★★ (5/5)')], decimal_places=1, max_digits=2),
        ),
    ]
